#!/bin/sh -x >/tmp/b.log

# servald for MIPS mesh extender bundleid
bundleid=D1057555117D5411AEC058DE8A38FA780F2886224588B67B6852FF8251CEF381

if [ $BUTTON = wps ]; then
  if [ $ACTION = pressed ]; then
    lua -e "print(os.time())" > /tmp/button_press_time
  fi    
  if [ $ACTION = released ]; then
     presstime=`cat /tmp/button_press_time`
     buttondowntime=`lua -e "print(os.time()-"${presstime}")"`
     echo $buttondowntime > /tmp/button_down_time
     if [ $buttondowntime -lt 5 ]; then
       if [ -e /dos/servald ]; then
          # Copy in new servald binary from fat partition on
          # usb memory stick
          mv /serval/servald /serval/servald.old
          /serval/servald.old stop
          mv /dos/servald /serval/servald
       else
          if [ -e /dos/SERVALD ]; then 
            # Copy in new servald binary from fat partition on
            # usb memory stick
            mv /serval/servald /serval/servald.old
            /serval/servald.old stop
            mv /dos/servald /serval/servald
          else
            # see if there is an updated version of servald from rhizome
            /serval/servald rhizome extract file ${bundleid} /dos/servald
            if [ -e /dos/servald ]; then
              mv /serval/servald /serval/servald.old
              /serval/servald.old stop
              mv /dos/servald /serval/servald
            fi          
          fi
       fi 
     else
       # long press = factory reset
       mv /serval/servald /serval/servald.old
       /serval/servald.old stop
       cp /serval/servald.factory /serval/servald
     fi
     /serval/servald stop ; /serval/servald start
  fi
fi

