#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=41

start() {
  # Start servald
  mkdir /serval
  mount /dev/sda1 /serval
  export SERVALINSTANCE_PATH=/etc/serval
  mkdir -p $SERVALINSTANCE_PATH
  /serval/runservald &
}

stop() {
  export SERVALINSTANCE_PATH=/etc/serval
  /serval/servald stop
}
