#!/bin/bash -x

repository=http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/

kernelversion=`wget -q -O - ${repository}/packages/ | grep kmod-fs-vfat | cut -f2 -d_`
echo kernel version is $kernelversion

packagelist=`wget -q -O - ${repository}/packages/ | egrep "blkid_|block-mount|dosfsck|e2fsprogs|\"fdisk|libblkid|libcom_err|libext2fs|libpthread|libuuid|librt_|mkdosfs|swap-utils|tcpdump_|minicom|ncurses|terminfo|libpcap|mkdosfs|dosfsck|dosfslabel|cp437|usbreset" | cut -f2 -d\"`

rm mr3020-packages/*.ipk
for file in $packagelist kmod-fs-vfat_${kernelversion}_ar71xx.ipk kmod-fs-msdos_${kernelversion}_ar71xx.ipk kmod-fs-ext4_${kernelversion}_ar71xx.ipk kmod-lib-crc16_${kernelversion}_ar71xx.ipk kmod-scsi-core_${kernelversion}_ar71xx.ipk kmod-usb-serial-cp210x_${kernelversion}_ar71xx.ipk kmod-usb-serial-pl2303_${kernelversion}_ar71xx.ipk kmod-usb-serial_${kernelversion}_ar71xx.ipk kmod-usb-storage-extras_${kernelversion}_ar71xx.ipk kmod-usb-storage_${kernelversion}_ar71xx.ipk ; do
   wget -O mr3020-packages/$file ${repository}/packages/$file
done

rm openwrt-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin
wget ${repository}/openwrt-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin

./get_extra_files
