#!/bin/csh -f

mkdir -p tmp/staging
cd tmp
rm -fr staging
mkdir staging
cd staging
find .

wget -O packages.gz http://downloads.openwrt.org/snapshots/trunk/ar71xx/packages/Packages.gz
gunzip packages.gz

foreach p ( minicom_ libpcap libncurses_ terminfo_ mkdosfs_ dosfsck_ dosfslabel_ python coreutils bash procps curl_ sed_ gawk_ grep_ netcat_ chilli zlib tcpdump_)

  foreach f ( `grep "^Filename: ${p}" packages | cut -f2 -d" "`) 
     echo $f
     if ( ! -e ../../${f} ) then
        ( cd ../../ ; wget http://downloads.openwrt.org/snapshots/trunk/ar71xx/packages/${f} )
     endif
     tar zxvf ../../${f} data.tar.gz
     tar zxvf data.tar.gz
  end

end

rm data.tar.gz
mv usr/lib lib
mv lib/lib/* lib
mv usr/sbin sbin
mv usr/bin/* bin
mv usr/share share
mkdir include
mv usr/include/* include
mv include/* include
rmdir usr

cp ../../../mr3020-files/upgrade upgrade

tar zcvf ../../../mr3020-files/extra-files-serval.tgz sbin bin lib include upgrade
tar zcvf ../../../mr3020-files/extra-files-usr.tgz share

